# fly.toml app configuration file generated for countriesback on 2023-08-17T03:09:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "countriesback"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
